# https://docs.google.com/document/d/2fKTnCh1uSzBjXX5ZFBCLPx7JCMlMY8V7nbzSVbVyw56/edit
# GDOC key from URL is 2fKTnCh1uSzBjXX5ZFBCLPx7JCMlMY8V7nbzSVbVyw56
GDOC:
  key: "2fKTnCh1uSzBjXX5ZFBCLPx7JCMlMY8V7nbzSVbVyw56"
  email: "user@example.com"
  password: "secret"

FILES: # xliff files <=> gdoc tabs
  - "cockpit"
  - "common"
  - "desktop"
  - "error-msg"
  - "FOSUserBundle"
  - "home"
  - "learn"
  - "validators"
  - "test"

LANGUAGES:
  - "en"
  - "de"
